/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as YoutubeIndexRouteImport } from './routes/youtube.index'
import { Route as AdminCmsIndexRouteImport } from './routes/admin.cms.index'
import { Route as AdminCmsGalleryRouteImport } from './routes/admin.cms.gallery'
import { Route as AdminCmsGoogleReviewsRouteImport } from './routes/admin.cms.google-reviews'
import { Route as AdminCmsLoginRouteImport } from './routes/admin.cms.login'
import { Route as AdminCmsSettingsRouteImport } from './routes/admin.cms.settings'
import { Route as AdminCmsYoutubeRouteImport } from './routes/admin.cms.youtube'
import { Route as ApiCmsGalleryRouteImport } from './routes/api.cms.gallery'
import { Route as ApiCmsYoutubeRouteImport } from './routes/api.cms.youtube'
import { Route as ApiPublicGalleryRouteImport } from './routes/api.public.gallery'
import { Route as ApiPublicGoogleReviewsRouteImport } from './routes/api.public.google-reviews'
import { Route as ApiPublicYoutubeRouteImport } from './routes/api.public.youtube'
import { Route as YoutubePlaylistPlaylistIdRouteImport } from './routes/youtube.playlist.$playlistId'
import { Route as ApiCmsAuthLoginRouteImport } from './routes/api.cms.auth.login'
import { Route as ApiCmsAuthLogoutRouteImport } from './routes/api.cms.auth.logout'
import { Route as ApiCmsAuthMeRouteImport } from './routes/api.cms.auth.me'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/admin/cms',
  path: '/admin/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursesRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JournalRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const YoutubeIndexRoute = YoutubeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YoutubeRoute,
} as any)
const AdminCmsIndexRoute = AdminCmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsGalleryRoute = AdminCmsGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsGoogleReviewsRoute = AdminCmsGoogleReviewsRouteImport.update({
  id: '/google-reviews',
  path: '/google-reviews',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsLoginRoute = AdminCmsLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsSettingsRoute = AdminCmsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminCmsRoute,
} as any)
const AdminCmsYoutubeRoute = AdminCmsYoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => AdminCmsRoute,
} as any)
const ApiCmsGalleryRoute = ApiCmsGalleryRouteImport.update({
  id: '/api/cms/gallery',
  path: '/api/cms/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsYoutubeRoute = ApiCmsYoutubeRouteImport.update({
  id: '/api/cms/youtube',
  path: '/api/cms/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGalleryRoute = ApiPublicGalleryRouteImport.update({
  id: '/api/public/gallery',
  path: '/api/public/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGoogleReviewsRoute = ApiPublicGoogleReviewsRouteImport.update({
  id: '/api/public/google-reviews',
  path: '/api/public/google-reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYoutubeRoute = ApiPublicYoutubeRouteImport.update({
  id: '/api/public/youtube',
  path: '/api/public/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubePlaylistPlaylistIdRoute =
  YoutubePlaylistPlaylistIdRouteImport.update({
    id: '/playlist/$playlistId',
    path: '/playlist/$playlistId',
    getParentRoute: () => YoutubeRoute,
  } as any)
const ApiCmsAuthLoginRoute = ApiCmsAuthLoginRouteImport.update({
  id: '/api/cms/auth/login',
  path: '/api/cms/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsAuthLogoutRoute = ApiCmsAuthLogoutRouteImport.update({
  id: '/api/cms/auth/logout',
  path: '/api/cms/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsAuthMeRoute = ApiCmsAuthMeRouteImport.update({
  id: '/api/cms/auth/me',
  path: '/api/cms/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/journal': typeof JournalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/youtube': typeof YoutubeRouteWithChildren
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/courses/$slug': typeof CoursesSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/youtube/': typeof YoutubeIndexRoute
  '/admin/cms/gallery': typeof AdminCmsGalleryRoute
  '/admin/cms/google-reviews': typeof AdminCmsGoogleReviewsRoute
  '/admin/cms/login': typeof AdminCmsLoginRoute
  '/admin/cms/settings': typeof AdminCmsSettingsRoute
  '/admin/cms/youtube': typeof AdminCmsYoutubeRoute
  '/api/cms/gallery': typeof ApiCmsGalleryRoute
  '/api/cms/youtube': typeof ApiCmsYoutubeRoute
  '/api/public/gallery': typeof ApiPublicGalleryRoute
  '/api/public/google-reviews': typeof ApiPublicGoogleReviewsRoute
  '/api/public/youtube': typeof ApiPublicYoutubeRoute
  '/youtube/playlist/$playlistId': typeof YoutubePlaylistPlaylistIdRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/api/cms/auth/login': typeof ApiCmsAuthLoginRoute
  '/api/cms/auth/logout': typeof ApiCmsAuthLogoutRoute
  '/api/cms/auth/me': typeof ApiCmsAuthMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/courses': typeof CoursesIndexRoute
  '/journal': typeof JournalIndexRoute
  '/youtube': typeof YoutubeIndexRoute
  '/admin/cms/gallery': typeof AdminCmsGalleryRoute
  '/admin/cms/google-reviews': typeof AdminCmsGoogleReviewsRoute
  '/admin/cms/login': typeof AdminCmsLoginRoute
  '/admin/cms/settings': typeof AdminCmsSettingsRoute
  '/admin/cms/youtube': typeof AdminCmsYoutubeRoute
  '/api/cms/gallery': typeof ApiCmsGalleryRoute
  '/api/cms/youtube': typeof ApiCmsYoutubeRoute
  '/api/public/gallery': typeof ApiPublicGalleryRoute
  '/api/public/google-reviews': typeof ApiPublicGoogleReviewsRoute
  '/api/public/youtube': typeof ApiPublicYoutubeRoute
  '/youtube/playlist/$playlistId': typeof YoutubePlaylistPlaylistIdRoute
  '/admin/cms': typeof AdminCmsIndexRoute
  '/api/cms/auth/login': typeof ApiCmsAuthLoginRoute
  '/api/cms/auth/logout': typeof ApiCmsAuthLogoutRoute
  '/api/cms/auth/me': typeof ApiCmsAuthMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRouteWithChildren
  '/faculty': typeof FacultyRoute
  '/faq': typeof FaqRoute
  '/gallery': typeof GalleryRoute
  '/journal': typeof JournalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/results': typeof ResultsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/youtube': typeof YoutubeRouteWithChildren
  '/admin/cms': typeof AdminCmsRouteWithChildren
  '/courses/$slug': typeof CoursesSlugRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/courses/': typeof CoursesIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/youtube/': typeof YoutubeIndexRoute
  '/admin/cms/gallery': typeof AdminCmsGalleryRoute
  '/admin/cms/google-reviews': typeof AdminCmsGoogleReviewsRoute
  '/admin/cms/login': typeof AdminCmsLoginRoute
  '/admin/cms/settings': typeof AdminCmsSettingsRoute
  '/admin/cms/youtube': typeof AdminCmsYoutubeRoute
  '/api/cms/gallery': typeof ApiCmsGalleryRoute
  '/api/cms/youtube': typeof ApiCmsYoutubeRoute
  '/api/public/gallery': typeof ApiPublicGalleryRoute
  '/api/public/google-reviews': typeof ApiPublicGoogleReviewsRoute
  '/api/public/youtube': typeof ApiPublicYoutubeRoute
  '/youtube/playlist/$playlistId': typeof YoutubePlaylistPlaylistIdRoute
  '/admin/cms/': typeof AdminCmsIndexRoute
  '/api/cms/auth/login': typeof ApiCmsAuthLoginRoute
  '/api/cms/auth/logout': typeof ApiCmsAuthLogoutRoute
  '/api/cms/auth/me': typeof ApiCmsAuthMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/faculty'
    | '/faq'
    | '/gallery'
    | '/journal'
    | '/privacy'
    | '/results'
    | '/sitemap.xml'
    | '/terms'
    | '/youtube'
    | '/admin/cms'
    | '/courses/$slug'
    | '/journal/$slug'
    | '/courses/'
    | '/journal/'
    | '/youtube/'
    | '/admin/cms/gallery'
    | '/admin/cms/google-reviews'
    | '/admin/cms/login'
    | '/admin/cms/settings'
    | '/admin/cms/youtube'
    | '/api/cms/gallery'
    | '/api/cms/youtube'
    | '/api/public/gallery'
    | '/api/public/google-reviews'
    | '/api/public/youtube'
    | '/youtube/playlist/$playlistId'
    | '/admin/cms/'
    | '/api/cms/auth/login'
    | '/api/cms/auth/logout'
    | '/api/cms/auth/me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faculty'
    | '/faq'
    | '/gallery'
    | '/privacy'
    | '/results'
    | '/sitemap.xml'
    | '/terms'
    | '/courses/$slug'
    | '/journal/$slug'
    | '/courses'
    | '/journal'
    | '/youtube'
    | '/admin/cms/gallery'
    | '/admin/cms/google-reviews'
    | '/admin/cms/login'
    | '/admin/cms/settings'
    | '/admin/cms/youtube'
    | '/api/cms/gallery'
    | '/api/cms/youtube'
    | '/api/public/gallery'
    | '/api/public/google-reviews'
    | '/api/public/youtube'
    | '/youtube/playlist/$playlistId'
    | '/admin/cms'
    | '/api/cms/auth/login'
    | '/api/cms/auth/logout'
    | '/api/cms/auth/me'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/courses'
    | '/faculty'
    | '/faq'
    | '/gallery'
    | '/journal'
    | '/privacy'
    | '/results'
    | '/sitemap.xml'
    | '/terms'
    | '/youtube'
    | '/admin/cms'
    | '/courses/$slug'
    | '/journal/$slug'
    | '/courses/'
    | '/journal/'
    | '/youtube/'
    | '/admin/cms/gallery'
    | '/admin/cms/google-reviews'
    | '/admin/cms/login'
    | '/admin/cms/settings'
    | '/admin/cms/youtube'
    | '/api/cms/gallery'
    | '/api/cms/youtube'
    | '/api/public/gallery'
    | '/api/public/google-reviews'
    | '/api/public/youtube'
    | '/youtube/playlist/$playlistId'
    | '/admin/cms/'
    | '/api/cms/auth/login'
    | '/api/cms/auth/logout'
    | '/api/cms/auth/me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  FacultyRoute: typeof FacultyRoute
  FaqRoute: typeof FaqRoute
  GalleryRoute: typeof GalleryRoute
  JournalRoute: typeof JournalRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResultsRoute: typeof ResultsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  YoutubeRoute: typeof YoutubeRouteWithChildren
  AdminCmsRoute: typeof AdminCmsRouteWithChildren
  ApiCmsGalleryRoute: typeof ApiCmsGalleryRoute
  ApiCmsYoutubeRoute: typeof ApiCmsYoutubeRoute
  ApiPublicGalleryRoute: typeof ApiPublicGalleryRoute
  ApiPublicGoogleReviewsRoute: typeof ApiPublicGoogleReviewsRoute
  ApiPublicYoutubeRoute: typeof ApiPublicYoutubeRoute
  ApiCmsAuthLoginRoute: typeof ApiCmsAuthLoginRoute
  ApiCmsAuthLogoutRoute: typeof ApiCmsAuthLogoutRoute
  ApiCmsAuthMeRoute: typeof ApiCmsAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/admin/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof JournalRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/youtube/': {
      id: '/youtube/'
      path: '/'
      fullPath: '/youtube/'
      preLoaderRoute: typeof YoutubeIndexRouteImport
      parentRoute: typeof YoutubeRoute
    }
    '/admin/cms/': {
      id: '/admin/cms/'
      path: '/'
      fullPath: '/admin/cms/'
      preLoaderRoute: typeof AdminCmsIndexRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/gallery': {
      id: '/admin/cms/gallery'
      path: '/gallery'
      fullPath: '/admin/cms/gallery'
      preLoaderRoute: typeof AdminCmsGalleryRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/google-reviews': {
      id: '/admin/cms/google-reviews'
      path: '/google-reviews'
      fullPath: '/admin/cms/google-reviews'
      preLoaderRoute: typeof AdminCmsGoogleReviewsRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/login': {
      id: '/admin/cms/login'
      path: '/login'
      fullPath: '/admin/cms/login'
      preLoaderRoute: typeof AdminCmsLoginRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/settings': {
      id: '/admin/cms/settings'
      path: '/settings'
      fullPath: '/admin/cms/settings'
      preLoaderRoute: typeof AdminCmsSettingsRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/admin/cms/youtube': {
      id: '/admin/cms/youtube'
      path: '/youtube'
      fullPath: '/admin/cms/youtube'
      preLoaderRoute: typeof AdminCmsYoutubeRouteImport
      parentRoute: typeof AdminCmsRoute
    }
    '/api/cms/gallery': {
      id: '/api/cms/gallery'
      path: '/api/cms/gallery'
      fullPath: '/api/cms/gallery'
      preLoaderRoute: typeof ApiCmsGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/youtube': {
      id: '/api/cms/youtube'
      path: '/api/cms/youtube'
      fullPath: '/api/cms/youtube'
      preLoaderRoute: typeof ApiCmsYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gallery': {
      id: '/api/public/gallery'
      path: '/api/public/gallery'
      fullPath: '/api/public/gallery'
      preLoaderRoute: typeof ApiPublicGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-reviews': {
      id: '/api/public/google-reviews'
      path: '/api/public/google-reviews'
      fullPath: '/api/public/google-reviews'
      preLoaderRoute: typeof ApiPublicGoogleReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/youtube': {
      id: '/api/public/youtube'
      path: '/api/public/youtube'
      fullPath: '/api/public/youtube'
      preLoaderRoute: typeof ApiPublicYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/playlist/$playlistId': {
      id: '/youtube/playlist/$playlistId'
      path: '/playlist/$playlistId'
      fullPath: '/youtube/playlist/$playlistId'
      preLoaderRoute: typeof YoutubePlaylistPlaylistIdRouteImport
      parentRoute: typeof YoutubeRoute
    }
    '/api/cms/auth/login': {
      id: '/api/cms/auth/login'
      path: '/api/cms/auth/login'
      fullPath: '/api/cms/auth/login'
      preLoaderRoute: typeof ApiCmsAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/auth/logout': {
      id: '/api/cms/auth/logout'
      path: '/api/cms/auth/logout'
      fullPath: '/api/cms/auth/logout'
      preLoaderRoute: typeof ApiCmsAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/auth/me': {
      id: '/api/cms/auth/me'
      path: '/api/cms/auth/me'
      fullPath: '/api/cms/auth/me'
      preLoaderRoute: typeof ApiCmsAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoursesRouteChildren {
  CoursesSlugRoute: typeof CoursesSlugRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesSlugRoute: CoursesSlugRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

interface YoutubeRouteChildren {
  YoutubeIndexRoute: typeof YoutubeIndexRoute
  YoutubePlaylistPlaylistIdRoute: typeof YoutubePlaylistPlaylistIdRoute
}

const YoutubeRouteChildren: YoutubeRouteChildren = {
  YoutubeIndexRoute: YoutubeIndexRoute,
  YoutubePlaylistPlaylistIdRoute: YoutubePlaylistPlaylistIdRoute,
}

const YoutubeRouteWithChildren =
  YoutubeRoute._addFileChildren(YoutubeRouteChildren)

interface AdminCmsRouteChildren {
  AdminCmsGalleryRoute: typeof AdminCmsGalleryRoute
  AdminCmsGoogleReviewsRoute: typeof AdminCmsGoogleReviewsRoute
  AdminCmsLoginRoute: typeof AdminCmsLoginRoute
  AdminCmsSettingsRoute: typeof AdminCmsSettingsRoute
  AdminCmsYoutubeRoute: typeof AdminCmsYoutubeRoute
  AdminCmsIndexRoute: typeof AdminCmsIndexRoute
}

const AdminCmsRouteChildren: AdminCmsRouteChildren = {
  AdminCmsGalleryRoute: AdminCmsGalleryRoute,
  AdminCmsGoogleReviewsRoute: AdminCmsGoogleReviewsRoute,
  AdminCmsLoginRoute: AdminCmsLoginRoute,
  AdminCmsSettingsRoute: AdminCmsSettingsRoute,
  AdminCmsYoutubeRoute: AdminCmsYoutubeRoute,
  AdminCmsIndexRoute: AdminCmsIndexRoute,
}

const AdminCmsRouteWithChildren = AdminCmsRoute._addFileChildren(
  AdminCmsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRouteWithChildren,
  FacultyRoute: FacultyRoute,
  FaqRoute: FaqRoute,
  GalleryRoute: GalleryRoute,
  JournalRoute: JournalRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResultsRoute: ResultsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  YoutubeRoute: YoutubeRouteWithChildren,
  AdminCmsRoute: AdminCmsRouteWithChildren,
  ApiCmsGalleryRoute: ApiCmsGalleryRoute,
  ApiCmsYoutubeRoute: ApiCmsYoutubeRoute,
  ApiPublicGalleryRoute: ApiPublicGalleryRoute,
  ApiPublicGoogleReviewsRoute: ApiPublicGoogleReviewsRoute,
  ApiPublicYoutubeRoute: ApiPublicYoutubeRoute,
  ApiCmsAuthLoginRoute: ApiCmsAuthLoginRoute,
  ApiCmsAuthLogoutRoute: ApiCmsAuthLogoutRoute,
  ApiCmsAuthMeRoute: ApiCmsAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
